[tool.poetry]
name = "Aioplate"
version = "1.1"
description = "Telegram bot"
authors = ["Andrey Karchevsky <karych@karych.ru>"]

[tool.poetry.dependencies]
python = "^3.10"
aiogram = "2.21"
asyncpg = "^0.26.0"
sqlalchemy = "^1.4.39"
alembic = "^1.8.0"
tzlocal = "^4.2"
pydantic = "^1.9.1"
greenlet = "*"


[tool.poetry.dev-dependencies]
black = "22.6.0"
isort = "5.10.1"

[build-system]
requires = ["poetry-core>=1.0.8"]
build-backend = "poetry.core.masonry.api"